config/routes.rb
Rails.application.routes.draw do
  get 'signup', to: 'users#new', as: 'signup'
  get 'login', to: 'sessions#new', as: 'login'
  get 'upvote', to: 'questions#upvote', as: 'upvote'
  get 'upvote_answer', to: 'answers#upvote', as: 'upvote_answer'
  delete 'logout', to: 'sessions#destroy', as: 'logout'
  root 'main#index'
  get 'admin', to: 'admin#index', as: 'admin'
  post 'admin', to: 'admin#create', as: 'adminify'
  delete 'admin', to: 'admin#delete', as: 'delete'
  post 'deadmin', to: 'admin#remove', as: 'deadmin'
  resources :users
  resources :sessions
  resources :questions do
    resources :answers
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/answer.rb
class Answer < ApplicationRecord
  belongs_to :user
  belongs_to :question
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/question.rb
class Question < ApplicationRecord
  belongs_to :user
  has_many :answers
end

app/models/user.rb
class User < ApplicationRecord
  has_many :questions
  has_many :answers
  has_secure_password
  validates_uniqueness_of :email, :username
end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
  before_action :admin
  def index
    @users = User.all.where(admin:false)
    @admins = User.all.where(admin:true)
    all = User.all
    @others = all.select{|x| x != current_user}
    qs = Question.all
    @todays_questions = qs.select{|x| x.created_at.to_date == Date.current}
    ans = Answer.all
    @todays_answers = ans.select{|x| x.created_at.to_date == Date.current}
  end
  def create
    @user = User.find(params[:user_id])
    if @user.update(admin:true)
      flash[:alert]="#{@user.username} is now an admin!"
      redirect_to admin_path
    else
      flash[:alert]='An error occurred, try again.'
      redirect_to admin_path
    end
  end
  def remove
    @user = User.find(params[:user_id])
    if @user.update(admin:false)
      flash[:alert]="#{@user.username} is nolonger an admin!"
      redirect_to admin_path
    else
      flash[:alert]='An error occurred, try again.'
      redirect_to admin_path
    end
  end
  def delete
    @user = User.find(params[:user_id])
    if @user.delete
      flash[:alert]="User Deleted"
      redirect_to admin_path
    else
      flash[:alert]='An error occurred, try again.'
      redirect_to admin_path
    end
  end
end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController
  before_action :authorize, only: [:new, :edit, :destroy, :upvote]
  def new
    @question = Question.find(params[:question_id])
    @answer = Answer.new
  end
  def create
    # @question = Question.find(params[:question_id])
    @answer = Answer.new(answer_params.merge(user_id:current_user.id).merge(question_id:params[:question_id]))
    if @answer.save
      flash[:notice]= "Answer Created Succesfully!"
      redirect_to question_path(@answer.question)
    else
      render :new
    end
  end
  def edit
    @answer = Answer.find(params[:id])
  end
  def update
    @answer = Answer.find(params[:id])
    if @answer.update(answer_params)
      flash[:notice]= "Answer Updated Succesfully!"
      redirect_to question_path(@answer.question)
    else
      render :edit
    end
  end
  def destroy
    @answer = Answer.find(params[:id])
    @answer.destroy
    flash[:notice]= "Answer Deleted Succesfully!"
    redirect_to question_path(@answer.question)
  end
  def upvote
    @answer = Answer.find(params[:answer])
    if @answer.increment! :votes
      flash[:notice]="Answer Upvoted!"
    end
    redirect_to question_path(@answer.question)
  end

  private
  def answer_params
    params.require(:answer).permit(:description)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  private
  def current_user
    @current_user ||= User.find(session[:user_id]) if  session[:user_id]
  end
  helper_method :current_user
  def authorize
    if current_user.nil?
      flash[:alert] = 'Please Log In First'
      redirect_to login_path
    end
  end
  def admin
    if !current_user.admin
      flash[:alert] = 'Not Authorized!'
      redirect_to root_path
    end
  end
end

app/controllers/main_controller.rb
class MainController < ApplicationController
  def index
    @questions = Question.all.order('id ASC').reorder('votes DESC')
  end
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  before_action :authorize, only: [:new, :edit, :destroy, :upvote]
  def new
    @question = Question.new
  end
  def create
    @question = Question.new(question_params.merge(user_id:current_user.id))
    if @question.save
      flash[:notice]= "Question Created Succesfully!"
      redirect_to questions_path
    else
      render :new
    end
  end
  def index
    @questions = Question.all
  end
  def show
    @question = Question.find(params[:id])
  end
  def edit
    @question = Question.find(params[:id])
  end
  def update
    @question = Question.find(params[:id])
    if @question.update(question_params)
      flash[:notice]= "Question Updated Succesfully!"
      redirect_to question_path(@question)
    else
      render :edit
    end
  end
  def destroy
    @question = Question.find(params[:id])
    @question.destroy
    flash[:notice]= "Question Deleted Succesfully!"
    redirect_to questions_path
  end
  def upvote
    @question = Question.find(params[:question])
    if @question.increment! :votes
      flash[:notice]="Question Upvoted!"
    end
    redirect_to question_path(@question)
  end

  private
  def question_params
    params.require(:question).permit(:user_id,:title,:description)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  before_action :authorize, only: [:destroy]
  def new
  end
  def create
    user = User.find_by_email(params[:email])
    username = User.find_by_username(params[:email])
    if user && user.authenticate(params[:password])
      flash[:alert] = "Succesful"
      session[:user_id] = user.id
      redirect_to root_path
    elsif username && username.authenticate(params[:password])
      flash[:alert] = "Succesful"
      session[:user_id] = username.id
      redirect_to root_path
    else
      flash[:alert] = "Email or password wrong"
      render :new
    end
  end
  def destroy
    session[:user_id] = nil
    redirect_to root_path, alert:'Out you go!'
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end
  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      redirect_to root_path, notice:'Thanks for Signing Up!'
    else
     render :new
    end
  end
  def show
    @user = User.find(params[:id])
  end

  private
  def user_params
    params.require(:user).permit(:email,:password,:password_confirmation,:username,:first_name, :last_name)
  end
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/main_helper.rb
module MainHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admin/index.html.erb
<h2>This is where Admin actions are carried out!</h2>
<h4>System has <%= @others.count %> Users excluding yourself, <%= User.all.where(admin:true).select{|x| x != current_user}.count%> of which are admins.</h4>
<p>Questions asked today: <%= @todays_questions.count%> while <%= @todays_answers.count%> new answers have been recorded today.</p>
<div class="well">
  <h4>Make other users admins</h4>
  <%= form_tag admin_path do %>
      <%=  select_tag(:user_id, options_from_collection_for_select(@users, :id, :email)) %>
      <%= submit_tag 'Make Admin'%>
  <% end%>
</div>
<div class="well">
  <h4>Remove users as admins</h4>
  <%= form_tag deadmin_path do %>
      <%=  select_tag(:user_id, options_from_collection_for_select(@admins, :id, :email)) %>
      <%= submit_tag 'Remove Admin'%>
  <% end%>
</div>
<div class="">
  <h4>Delete Users</h4>
  <%= form_tag admin_path, method:'delete' do %>
      <%=  select_tag(:user_id, options_from_collection_for_select(@others, :id, :email)) %>
      <%= submit_tag 'Delete User', :data => {:confirm => "Are you sure?",
                                         :method => "delete"} %>
  <% end%>
</div>

app/views/answers/_form.html.erb
<%= render "layouts/errors", :object => @answer %>


<%= form_for [@question,@answer] do |f| %>
<%= f.label :description %>
<%= f.text_field :description %>
<%= f.submit %>
<% end %>

app/views/answers/edit.html.erb
<h1>Editing <%= @answer.description %></h1>

<%= render 'form' %>

app/views/answers/new.html.erb
<h1>Add a new comment to <%= @question.title%></h1>

<%= render 'form'%>

app/views/layouts/_errors.html.erb
<% if object.errors.any? %>
<h3>Please fix these errors:</h3>
<ul>
  <% object.errors.full_messages.each do |message| %>
  <li><%= message %></li>
  <% end %>
</ul>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>StackOverflow</title>
    <%= csrf_meta_tags %>
    <meta name="title" content="Rails Overflow">
    <meta name="description" content="A stack overflow clone in Rails.">

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= link_to 'Home Page', root_path%>
    <% if current_user%>
    Logged in as <%= current_user.email %>
    <%= link_to 'Log Out',  logout_path, method:'delete'%>
    <% if current_user.admin %>
    <%= link_to 'Go to Admin' ,admin_path%>
    <% end %>
    <%else%>
    <%= link_to 'Sign Up', signup_path%>
    <%= link_to 'Log In', login_path%>
    <%end%>
    <%= flash[:alert]%>
    <%= flash[:notice]%>
    <%= yield %>
  </body>
</html>

app/views/main/index.html.erb
<h3>Rails Overflow</h3>
<% if @questions.any? %>
<ul>
  <h4>Top Questions</h4>
  <% @questions.each do |question|%>
  <li>
   <%= link_to question.title, question_path(question) %> |
   by <%= link_to question.user.username, user_path(question.user) %> |
  <%= link_to 'Edit', edit_question_path(question) %> |
   <% if question.votes %>
   Votes: <%= question.votes %>
   <% else %>
   Be the first to vote it up!
   <% end %> |
   Answers: <%= question.answers.count%>
   </li>

<% end %>
</ul>
<%else%>
<h1>No questions yet</h1>
<%end%>

<hr>
<p><%= link_to "New Question", new_question_path%></p>

app/views/questions/_form.html.erb
<%= render "layouts/errors", :object => @question %>


<%= form_for [@question] do |f| %>
<%= f.label :title %>
<%= f.text_field :title %>
<%= f.label :description %>
<%= f.text_field :description %>
<%= f.submit %>
<% end %>

app/views/questions/edit.html.erb
<h3>Editing <%= @question.title%></h3>

<%= render 'form'%>

app/views/questions/index.html.erb
<h1>Rails Overflow</h1>
<% if @questions.any? %>
<ul>
  <% @questions.each do |question|%>
  <li>
   <%= link_to question.title, question_path(question) %> |
   by <%= link_to question.user.username, user_path(question.user) %> |
  <%= link_to 'Edit', edit_question_path(question) %> |
   <% if question.votes %>
   Votes: <%= question.votes %>
   <% else %>
   Be the first to vote it up!
   <% end %>
   </li>

<% end %>
</ul>
<%else%>
<h1>No questions yet</h1>
<%end%>

<hr>
<p><%= link_to "New Question", new_question_path%></p>

app/views/questions/new.html.erb
<h3>New Question</h3>

<%= render 'form'%>

app/views/questions/show.html.erb
<h1><%= @question.title%></h1>
<h3><%= @question.description%></h3>
<% if @question.votes %>
Votes:
<%= @question.votes %>
<% else %>
<small>Be the first to vote it up!</small>
<% end %><%= link_to 'Vote Up', upvote_path(question:@question)%>
Answers: <%= @question.answers.count%>
<% if current_user%>
<% if @question.answers.any?%>
<ul>
  <h4>Answers</h4>
  <% @question.answers.each do |answer| %>
  <li>
    <%=answer.description%>
    | by
    <%= link_to answer.user.username, user_path(answer.user)%>
    |
    <% if answer.votes %>
    Votes:
    <%= answer.votes %>
    <% else %>
    <small>Be the first to vote it up!</small>
    <% end %><%= link_to 'Vote Up', upvote_answer_path(answer:answer  )%>
    <% end %>
  </ul>
  <% else %>
  <h3>This Question has no answers yet!</h3>
  <small>Post One Now!</small>
  <% end %>
<% else %>
<h3>Please Log In To See Answers</h3>
<% end %>
<p><%= link_to 'New Answer', new_question_answer_path(@question)%></p>

<hr>
<p><%= link_to 'Edit Question', edit_question_path(@question)%></p>
<p><%= link_to 'Delete Question', question_path(@question),
                          :data => {:confirm => "Are you sure?",
                                         :method => "delete"}
                                         %></p>

app/views/users/new.html.erb
<h3>Sign Up</h3>
<%= render "layouts/errors", :object => @user %>
<%= form_for @user do |f| %>
<div class="field">
  <%= f.label :email %>
  <%= f.email_field :email %>
</div>
<div class="field">
  <%= f.label :username %>
  <%= f.text_field :username %>
</div>
<div class="field">
  <%= f.label :first_name %>
  <%= f.text_field :first_name %>
</div>
<div class="field">
  <%= f.label :last_name %>
  <%= f.text_field :last_name %>
</div>
<div class="field">
  <%= f.label :password %>
  <%= f.password_field :password %>
</div>
<div class="field">
  <%= f.label :password_confirmation %>
  <%= f.password_field :password_confirmation %>
</div>
<%= f.submit %>
<% end %>

app/views/users/show.html.erb
<h4><%= @user.username%></h4>
First Name: <%= @user.first_name%> |
Last Name: <%= @user.last_name%> |
Username: <%= @user.username%> |
Email: <%= @user.email%> |
Joined: <%= @user.created_at%> |
Questions Asked: <%= @user.questions.count%> |
Questions Answered: <%= @user.answers.count%> |